### ISSUE TITLE
Challenge category & tag pie charts

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juicy-statistics#20]
Currently I am running a CTFd instance with all Juice Shop challenges imported to make a screenshot every now and then of the current distribution of challenge categories. This image appears in the eBook as well as the intro presentation slides:

![](https://pwning.owasp-juice.shop/part1/img/categories.png)

It would be nice to have such a pie chart on https://stats.owasp-juice.shop instead. The necessary data should be pulled from https://github.com/OWASP/www-project-juice-shop/blob/master/_data/challenges.yml - that copy of the `challenges.yml` from the Juice Shop main repo is updated automatically on every release.

Another chart showing challenges by their tags would also be nice to have. Important: Other than with categories challenges can have multiple tags!

**Comment by bkimminich** [comment]
Both the category and tag information from that https://github.com/OWASP/www-project-juice-shop/blob/master/_data/challenges.yml is already read and presented in tabular form here: https://owasp.org/www-project-juice-shop/#div-challenges - The pie-chart presentation with % instead of absolute numbers would be a nice extra general information plus a screenshot source for the ebook and intro slide deck.

**Comment by the-pro** [comment]
I got something like this. Is this the correct distiribution

![categories](https://user-images.githubusercontent.com/42973786/119457833-bb79e900-bd59-11eb-955a-c8b692aca0b0.png)

**Comment by bkimminich** [comment]
Google has a wonky way of ordring the slices, but the Top 5 match in % value at least. Well done! 👍
