### ISSUE TITLE
Logarithmic scale does not work in BarCharts

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juicy-statistics#24]
```
        vAxis: {
            scaleType: 'log'
        }
```

or

```
        vAxis: {
            scaleType: 'mirrorLog'
        }
```

## ❌ No effect in BarCharts
![image](https://user-images.githubusercontent.com/3531020/208546986-03779c99-93cd-4c13-9542-2c7d20a40abd.png)
![image](https://user-images.githubusercontent.com/3531020/208547025-39a78cb0-8514-427b-a50d-930b3cf1cb6c.png)
![image](https://user-images.githubusercontent.com/3531020/208547058-a62629f1-9b84-4215-ba0e-bae5e4c89a7a.png)

## ✅ Works as intended in ComboChart for GitHub downloads
![image](https://user-images.githubusercontent.com/3531020/208546860-0c71238d-8513-469a-9f19-8a0884d0a0be.png)

**Comment by bkimminich** [comment]
GitHub barchart also no longer works, it even threw errors during rendering for a while. Now it shows a totally pointless axis scale leading to tiny bars only.

**Comment by parteekcoder** [comment]
@bkimminich is this issue solved or still need some work

**Comment by bkimminich** [comment]
> @bkimminich is this issue solved or still need some work

Yes, it's still open.

**Comment by bkimminich** [comment]
Fixed by switching to line diagram.
